*****           Implementation of object type SFLTRIP              *****
INCLUDE <OBJECT>.
BEGIN_DATA OBJECT. " Do not change.. DATA is generated
* only private members may be inserted into structure private
DATA:
" begin of private,
"   to declare private attributes remove comments and
"   insert private attributes here ...
" end of private,
  BEGIN OF KEY,
      TRAVELAGENCYNUMBER LIKE SFLTRIP-AGENCYNUM,
      TRIPNUMBER LIKE SFLTRIP-TRIPNUM,
  END OF KEY.
END_DATA OBJECT. " Do not change.. DATA is generated

BEGIN_METHOD GETLIST CHANGING CONTAINER.
DATA:
      TRAVELAGENCY LIKE BAPISTRKEY-AGENCYNUM,
      CUSTOMERNUMBER LIKE BAPISTRDAT-CUSTOMERID,
      MAXROWS LIKE BAPISTRAUX-BAPIMAXROW,
      TRIPDATERANGE LIKE BAPISCODRA OCCURS 0,
      BOOKINGDATERANGE LIKE BAPISCODRA OCCURS 0,
      EXTENSIONIN LIKE BAPIPAREX OCCURS 0,
      FLIGHTTRIPLIST LIKE BAPISTRDAT OCCURS 0,
      EXTENSIONOUT LIKE BAPIPAREX OCCURS 0,
      RETURN LIKE BAPIRET2 OCCURS 0.
  SWC_GET_ELEMENT CONTAINER 'TravelAgency' TRAVELAGENCY.
  SWC_GET_ELEMENT CONTAINER 'CustomerNumber' CUSTOMERNUMBER.
  SWC_GET_ELEMENT CONTAINER 'MaxRows' MAXROWS.
  SWC_GET_TABLE CONTAINER 'TripDateRange' TRIPDATERANGE.
  SWC_GET_TABLE CONTAINER 'BookingDateRange' BOOKINGDATERANGE.
  SWC_GET_TABLE CONTAINER 'ExtensionIn' EXTENSIONIN.
  CALL FUNCTION 'BAPI_FLTRIP_GETLIST'
    EXPORTING
      MAX_ROWS = MAXROWS
      CUSTOMER_NUMBER = CUSTOMERNUMBER
      TRAVEL_AGENCY = TRAVELAGENCY
    TABLES
      RETURN = RETURN
      EXTENSION_OUT = EXTENSIONOUT
      FLIGHT_TRIP_LIST = FLIGHTTRIPLIST
      EXTENSION_IN = EXTENSIONIN
      BOOKING_DATE_RANGE = BOOKINGDATERANGE
      TRIP_DATE_RANGE = TRIPDATERANGE
    EXCEPTIONS
      OTHERS = 01.
  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN OTHERS.       " to be implemented
  ENDCASE.
  SWC_SET_TABLE CONTAINER 'FlightTripList' FLIGHTTRIPLIST.
  SWC_SET_TABLE CONTAINER 'ExtensionOut' EXTENSIONOUT.
  SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD CREATE CHANGING CONTAINER.
DATA:
      FLIGHTTRIPDATA LIKE BAPISTRNEW,
      TICKETPRICE LIKE BAPISTRPRI,
      PASSENGERLIST LIKE BAPISTRPAS OCCURS 0,
      EXTENSIONIN LIKE BAPIPAREX OCCURS 0,
      RETURN LIKE BAPIRET2 OCCURS 0.
  SWC_GET_ELEMENT CONTAINER 'FlightTripData' FLIGHTTRIPDATA.
  SWC_GET_TABLE CONTAINER 'PassengerList' PASSENGERLIST.
  SWC_GET_TABLE CONTAINER 'ExtensionIn' EXTENSIONIN.
  CALL FUNCTION 'BAPI_FLTRIP_CREATE'
    EXPORTING
      FLIGHT_TRIP_DATA = FLIGHTTRIPDATA
    IMPORTING
      TRAVELAGENCYNUMBER = OBJECT-KEY-TRAVELAGENCYNUMBER
      TRIPNUMBER = OBJECT-KEY-TRIPNUMBER
      TICKET_PRICE = TICKETPRICE
    TABLES
      PASSENGER_LIST = PASSENGERLIST
      EXTENSION_IN = EXTENSIONIN
      RETURN = RETURN
    EXCEPTIONS
      OTHERS = 01.
  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN OTHERS.       " to be implemented
  ENDCASE.
  SWC_SET_ELEMENT CONTAINER 'TicketPrice' TICKETPRICE.
  SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD CANCEL CHANGING CONTAINER.
DATA:
      RETURN LIKE BAPIRET2 OCCURS 0.
  CALL FUNCTION 'BAPI_FLTRIP_CANCEL'
    EXPORTING
      TRAVELAGENCYNUMBER = OBJECT-KEY-TRAVELAGENCYNUMBER
      TRIPNUMBER = OBJECT-KEY-TRIPNUMBER
    TABLES
      RETURN = RETURN
    EXCEPTIONS
      OTHERS = 01.
  CASE SY-SUBRC.
    WHEN 0.            " OK
    WHEN OTHERS.       " to be implemented
  ENDCASE.
  SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.
